<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Retro.Crt.Invaders</RootNamespace>
    <AssemblyName>Retro.Crt.Invaders</AssemblyName>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Retro.Crt\Retro.Crt.csproj" />
  </ItemGroup>

</Project>
